# -*- coding: utf-8 -*-
"""plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZAnCv-Ftl5A2XlC7piWC_ar-W894NLu
"""

import matplotlib.pyplot as plt
import numpy as np

# Data
configurations = ['Q_Win5_Act3', 'Q_Win6_Act3', 'Q_Win5_Act4', 'Q_Win7_Act3',
                  'Q_Win6_Act4', 'Q_Win5_Act5', 'Q_Win7_Act4', 'Q_Win6_Act5', 'Q_Win7_Act5']
duration_without_penalty = [43027.459435423276, 42688.25507251628, 42272.35106540198,
                            42755.4300697882, 42451.89600504681, 42825.10386937382,
                            42943.54729768673, 42360.23826136374, 42453.11521566863]
num_checkpoints = [128, 143, 160, 142, 155, 132, 127, 158, 152]
total_duration = [44947.459435423276, 44833.25507251628, 44672.35106540198,
                  44885.4300697882, 44776.89600504681, 44805.10386937382,
                  44848.54729768673, 44730.23826136374, 44733.11521566863]

# Plotting
fig, ax1 = plt.subplots()

# Bar width
bar_width = 0.35

# Positions for bars
r1 = np.arange(len(configurations))
r2 = [x + bar_width for x in r1]

# Plotting bars for Duration without Checkpoint Penalty and Total Duration
ax1.bar(r1, duration_without_penalty, color='b', width=bar_width, edgecolor='grey', label='Duration without Checkpoint Penalty')
ax1.bar(r2, total_duration, color='r', width=bar_width, edgecolor='grey', label='Total Duration')

# Creating a secondary y-axis for Number of Checkpoints
ax2 = ax1.twinx()
ax2.plot(r1, num_checkpoints, color='g', marker='o', label='Number of Checkpoints')

# X-axis labels
ax1.set_xlabel('Q Table Size', fontweight='bold')

# Y-axis labels
ax1.set_ylabel('Duration (Value)', color='b', fontweight='bold')
ax2.set_ylabel('Number of Checkpoints', color='g', fontweight='bold')

# Title
plt.title('Simulation Metrics', fontweight='bold')

# Set custom y-axis range for each set of data
ax1.set_ylim(42000, 45000)  # Adjust the range for Duration without Checkpoint Penalty and Total Duration
ax2.set_ylim(120, 165)  # Adjust the range for Number of Checkpoints

# Tilt x-axis labels
ax1.set_xticks(r1 + bar_width / 2)
ax1.set_xticklabels(configurations, rotation=45, ha='right', position=(-0.5, 0))
# Adding legend
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')

# Show plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data
exploration_fraction = [0.01, 0.05, 0.1]
duration_without_checkpointing = [42638.41562133234, 43507.30848942281, 42451.89600504681]
num_checkpoints = [145, 113, 155]
total_duration_with_checkpoints = [44813.41562133234, 45202.30848942281, 44776.89600504681]

# Plotting
fig, ax1 = plt.subplots()

# Bar width
bar_width = 0.2

# Positions for bars
r1 = np.arange(len(exploration_fraction))
r2 = [x + bar_width for x in r1]
r3 = [x + bar_width for x in r2]
r4 = [x + bar_width for x in r3]

# Plotting bars for Duration without Checkpointing and Total Duration with Checkpoints
ax1.bar(r1, duration_without_checkpointing, color='b', width=bar_width, edgecolor='grey', label='Duration without Checkpointing')
ax1.bar(r3, total_duration_with_checkpoints, color='r', width=bar_width, edgecolor='grey', label='Total Duration with Checkpoints')

# Creating a secondary y-axis for Number of Checkpoints
ax2 = ax1.twinx()
ax2.plot(r2, num_checkpoints, color='g', marker='o', label='Number of Checkpoints')

# X-axis labels
ax1.set_xlabel('Exploration Fraction', fontweight='bold')

# Y-axis labels
ax1.set_ylabel('Duration (Value)', color='b', fontweight='bold')
ax2.set_ylabel('Number of Checkpoints', color='g', fontweight='bold')

# Title
plt.title('Simulation Metrics with Different Exploration Fractions', fontweight='bold')

# X-axis ticks
plt.xticks([r + bar_width / 2 for r in range(len(exploration_fraction))], exploration_fraction)

# Y-axis range
ax1.set_ylim(41000, 46000)  # Adjust the range of the y-axis for Duration
ax2.set_ylim(100, 200)  # Adjust the range of the y-axis for Number of Checkpoints

# Adding legend
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')

# Show plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data
checkpoint_penalty = [5, 10, 15]
duration_without_checkpointing = [40205.08099072284, 41379.69168948355, 42451.89600504681]
num_checkpoints = [366, 215, 155]
total_duration_with_checkpoints = [43865.08099072284, 43529.69168948355, 44776.89600504681]

# Plotting
fig, ax1 = plt.subplots()

# Bar width
bar_width = 0.25

# Positions for bars
r1 = np.arange(len(checkpoint_penalty))
r2 = [x + bar_width for x in r1]

# Plotting bars for Duration without Checkpointing and Total Duration with Checkpoints
ax1.bar(r1, duration_without_checkpointing, color='b', width=bar_width, edgecolor='grey', label='Duration without Checkpointing')
ax1.bar(r2, total_duration_with_checkpoints, color='r', width=bar_width, edgecolor='grey', label='Total Duration with Checkpoints')

# Creating a secondary y-axis for Number of Checkpoints
ax2 = ax1.twinx()
ax2.plot(r1, num_checkpoints, color='g', marker='o', label='Number of Checkpoints')

# X-axis labels
ax1.set_xlabel('Checkpoint Penalty', fontweight='bold')

# Y-axis labels
ax1.set_ylabel('Duration / Total Duration (Value)', color='b', fontweight='bold')
ax2.set_ylabel('Number of Checkpoints', color='g', fontweight='bold')

# Title
plt.title('Simulation Metrics with Different Checkpoint Penalties', fontweight='bold')

# X-axis ticks
plt.xticks([r + bar_width / 2 for r in range(len(checkpoint_penalty))], checkpoint_penalty)

# Y-axis range
ax1.set_ylim(40000, 45000)  # Adjust the range of the y-axis for Duration and Total Duration
ax2.set_ylim(100, 400)  # Adjust the range of the y-axis for Number of Checkpoints

# Adding legend
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')

# Show plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data
checkpoint_penalty = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
total_duration_with_checkpointing = [
    43226.89600504681, 44001.89600504681, 44776.89600504681, 45551.89600504681, 46326.89600504681,
    47101.89600504681, 47876.89600504681, 48651.89600504681, 49426.89600504681, 50201.89600504681,
    50976.89600504681, 51751.89600504681, 52526.89600504681, 53301.89600504681, 54076.89600504681,
    54851.89600504681, 55626.89600504681, 56401.89600504681, 57176.89600504681, 57951.89600504681
]

# Plot
plt.figure(figsize=(10, 6))
plt.plot(checkpoint_penalty, total_duration_with_checkpointing, marker='o', linestyle='-')
plt.title('RL Forecast- Checkpoint Penalty vs Total Duration')
plt.xlabel('Checkpoint Penalty')
plt.ylabel('Total Duration with Checkpointing')
plt.grid(True)
plt.xticks(checkpoint_penalty)
plt.tight_layout()

# Show plot
plt.show()

import matplotlib.pyplot as plt

# Given data
q_table = ['Q53', 'Q63', 'Q54', 'Q73', 'Q64', 'Q55', 'Q74', 'Q65', 'Q75']
time_to_generate_model = [27, 36, 51, 57, 64, 41, 49, 75, 102]

# Create plot
plt.figure(figsize=(10, 6))
plt.plot(q_table, time_to_generate_model, marker='o', linestyle='-')

# Title and labels
plt.title('QTable vs. Time to Generate Model')
plt.xlabel('QTable')
plt.ylabel('Time to Generate Model (seconds)')

# Show plot
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.grid(True)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data from the image
checkpoint_penalty = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
total_duration = [47822, 48677, 49331, 50026, 50720, 51321, 51834, 52080, 52557, 53043, 53365, 53705, 53940, 54245, 54739,
                  55042, 55407, 55568, 55647, 56070]
best_window_size = [3, 4, 3, 9, 4, 7, 5, 5, 5, 5, 5, 6, 10, 10, 6, 6, 7, 7, 7, 7]

# Adjusting the plot to ensure all checkpoint penalties are clearly visible on the x-axis

fig, ax1 = plt.subplots(figsize=(10, 6))

# Plotting the Total Duration
ax1.plot(checkpoint_penalty, total_duration, 'b-', label='Total Duration', marker='o')
ax1.set_xlabel('Checkpoint Penalty')
ax1.set_ylabel('Total Duration', color='black')
ax1.tick_params('y', colors='black')

# Setting all checkpoint penalties on x-axis
ax1.set_xticks(checkpoint_penalty)

# Plotting Best Window Size on a secondary axis
ax2 = ax1.twinx()
ax2.plot(checkpoint_penalty, best_window_size, 'r-', label='Best Window Size', marker='s')
ax2.set_ylabel('Best Window Size', color='black')
ax2.tick_params('y', colors='black')

# Title and grid
plt.title('Total Duration and Best Window Size vs. Checkpoint Penalty')
ax1.grid(True)

plt.show()

import matplotlib.pyplot as plt

# Data from the image
checkpoint_penalty = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
total_duration = [47822, 48677, 49331, 50026, 50720, 51321, 51834, 52080, 52557, 53043, 53365, 53705, 53940, 54245, 54739,
                  55042, 55407, 55568, 55647, 56070]
best_window_size = [3, 4, 3, 9, 4, 7, 5, 5, 5, 5, 5, 6, 10, 10, 6, 6, 7, 7, 7, 7]

# Adjusting the plot to ensure all checkpoint penalties are clearly visible on the x-axis
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plotting the Total Duration
ax1.plot(checkpoint_penalty, total_duration, 'b-', label='Total Duration (s)', marker='o')
ax1.set_xlabel('Checkpoint Penalty (s)')
ax1.set_ylabel('Total Duration (s)', color='black')
ax1.tick_params('y', colors='black')

# Setting all checkpoint penalties on x-axis
ax1.set_xticks(checkpoint_penalty)

# Plotting Best Window Size on a secondary axis
ax2 = ax1.twinx()
ax2.plot(checkpoint_penalty, best_window_size, 'r-', label='Best Window Size', marker='s')
ax2.set_ylabel('Best Window Size', color='black')
ax2.tick_params('y', colors='black')

# Adding legends for both axes
ax1.legend(loc='upper left', bbox_to_anchor=(0, 1), frameon=False)  # Legend for Total Duration
ax2.legend(loc='upper left', bbox_to_anchor=(0, 0.95), frameon=False)

# Title and grid
plt.title('Dynamic MPC Total Duration and Best Window Size vs. Checkpoint Penalty')
ax1.grid(True)

plt.show()



import matplotlib.pyplot as plt

# Updated data from the image
checkpoint_penalty = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
total_duration = [48028, 49159, 50011, 50756, 51192, 51942, 52297, 53162, 53670, 54091, 54732, 55237, 55598, 56028, 56794,
                  57223, 57633, 57749, 58046, 58524]
best_window_size = [4, 6, 2, 7, 3, 6, 3, 6, 9, 9, 4, 4, 10, 10, 9, 9, 9, 8, 8, 8]

# Adjusting the plot to ensure all checkpoint penalties are clearly visible on the x-axis
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plotting the Total Duration
ax1.plot(checkpoint_penalty, total_duration, 'b-', label='Total Duration (s)', marker='o')
ax1.set_xlabel('Checkpoint Penalty (s)')
ax1.set_ylabel('Total Duration (s)', color='black')
ax1.tick_params('y', colors='black')

# Setting all checkpoint penalties on x-axis
ax1.set_xticks(checkpoint_penalty)

# Plotting Best Window Size on a secondary axis
ax2 = ax1.twinx()
ax2.plot(checkpoint_penalty, best_window_size, 'r-', label='Best Window Size', marker='s')
ax2.set_ylabel('Best Window Size', color='black')
ax2.tick_params('y', colors='black')

# Adding legends for both axes
# Set the location of legends to be below one another on the left
ax1.legend(loc='upper left', bbox_to_anchor=(0, 1), frameon=False)  # Legend for Total Duration
ax2.legend(loc='upper left', bbox_to_anchor=(0, 0.95), frameon=False)  # Legend for Best Window Size

# Title and grid
plt.title('Dynamic Window Total Duration and Best Window Size vs. Checkpoint Penalty')
ax1.grid(True)

plt.show()

import matplotlib.pyplot as plt

# Data for plotting
checkpoint_penalty = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95]
static_window = [47965, 49875, 51205, 52535, 53865, 55195, 55998, 56737, 57397, 58057]
dynamic_window = [48028, 50011, 51192, 52297, 53670, 54732, 55598, 56794, 57633, 58046]
dynamic_mpc = [47822, 49331, 50720, 51834, 52557, 53365, 53940, 54739, 55407, 55647]
reinforcement_learning = [47494.04055, 49158.03209, 50508.03209, 51829.50604, 53099.50604,
                         54369.50604, 55605.42788, 56835.42788, 58065.42788, 59295.42788]

# Create plot
plt.figure(figsize=(10, 6))

plt.plot(checkpoint_penalty, static_window, label="Static Window", marker='o')
plt.plot(checkpoint_penalty, dynamic_window, label="Dynamic Window", marker='o')
plt.plot(checkpoint_penalty, dynamic_mpc, label="Dynamic MPC", marker='o')
plt.plot(checkpoint_penalty, reinforcement_learning, label="Reinforcement Learning", marker='o')

# Adding titles and labels
plt.title("Checkpoint Penalty vs Total Duration")
plt.xlabel("Checkpoint Penalty (s)")
plt.ylabel("Total Duration (s)")
plt.legend()

# Show all checkpoint penalties on the x-axis
plt.xticks(checkpoint_penalty)

# Display the plot
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

# Data for plotting
checkpoint_penalty = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95]
static_window_checkpoints = [199, 133, 133, 133, 133, 133, 79, 66, 66, 66]
dynamic_window_checkpoints = [344, 202, 135, 133, 112, 101, 90, 94, 93, 84]
dynamic_mpc_checkpoints = [335, 180, 141, 123, 94, 84, 79, 68, 64, 57]
reinforcement_learning_checkpoints = [186, 135, 135, 127, 127, 127, 123, 123, 123, 123]

# Create plot
plt.figure(figsize=(10, 6))

plt.plot(checkpoint_penalty, static_window_checkpoints, label="Static Window", marker='o')
plt.plot(checkpoint_penalty, dynamic_window_checkpoints, label="Dynamic Window", marker='o')
plt.plot(checkpoint_penalty, dynamic_mpc_checkpoints, label="Dynamic MPC", marker='o')
plt.plot(checkpoint_penalty, reinforcement_learning_checkpoints, label="Reinforcement Learning", marker='o')

# Adding titles and labels
plt.title("Checkpoint Penalty vs Number of Checkpoints")
plt.xlabel("Checkpoint Penalty (s)")
plt.ylabel("Number of Checkpoints")
plt.legend()

# Show all checkpoint penalties on the x-axis
plt.xticks(checkpoint_penalty)

# Display the plot
plt.grid(True)
plt.show()



import matplotlib.pyplot as plt

# New data from the table
strategies = ['Static Window(3)', 'Dynamic Window(2)', 'Dynamic MPC(3)', 'Reinforcement Learning(3*10)']
tasks = ['3', '4', '5', '6', '7', '8']
values = [
    [133, 133, 133, 133, 133, 133],       # Static Window(3)
    [199, 199, 199, 202, 204, 202],       # Dynamic Window(2)
    [20, 104, 118, 139, 156, 180],        # Dynamic MPC(3)
    [399, 399, 399, 359, 180, 135]        # Reinforcement Learning(3*10)
]

# Plotting
plt.figure(figsize=(10, 6))
for strategy, value in zip(strategies, values):
    plt.plot(tasks, value, marker='o', label=strategy)

# Adding labels and title
plt.xlabel('Number of Tasks')
plt.ylabel('Number of Checkpoints')
plt.title('Number of Tasks Vs Number of Checkpoints')
plt.legend()
plt.grid(visible=True, linestyle='--', alpha=0.5)

# Show the plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data from the table
strategies = ['Static Window(3)', 'Dynamic Window(2)', 'Dynamic MPC(3)', 'Reinforcement Learning(3*10)']
tasks = ['3', '4', '5', '6', '7', '8']
values = [
    [25612, 26377, 29567, 35674, 42051, 49875],  # Static Window(3)
    [26663, 27320, 30328, 36068, 42608, 50011],  # Dynamic Window(2)
    [22851, 23841, 28721, 34926, 41470, 49331],  # Dynamic MPC(3)
    [29269, 30414, 33826, 38444, 42129, 49158]   # Reinforcement Learning(3*10)
]

# Plotting
plt.figure(figsize=(10, 6))
for strategy, value in zip(strategies, values):
    plt.plot(tasks, value, marker='o', label=strategy)

# Adding labels and title
plt.xlabel('Number of Tasks')
plt.ylabel('Total Duration (s)')
plt.title('Total Duration V/s Number of Tasks')
plt.legend()
plt.grid(visible=True, linestyle='--', alpha=0.5)

# Show the plot
plt.tight_layout()
plt.show()

import itertools
import pandas as pd

# Define the ranges
w_values = range(1, 11)  # w is 1 to 10
c_values = range(5, 96, 10)  # c is 5 to 95 with an interval of 10
sim_len_values = range(100, 801, 100)  # sim len is 100 to 800 with an interval of 100
num_tasks_values = range(1, 17)  # num tasks is 1 to 16 with an interval of 1

# Generate all possible combinations
combinations = list(itertools.product(w_values, c_values, sim_len_values, num_tasks_values))

# Create a DataFrame for better visualization and saving
combinations_df = pd.DataFrame(combinations, columns=["w", "c", "sim_len", "num_tasks"])

# Save to a file
output_path = "/content/sample_data/possible_combinations.xlsx"
combinations_df.to_excel(output_path, index=False)

output_path

import matplotlib.pyplot as plt

# Data for plotting
checkpoint_penalty = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

# Total duration data
static_window = [47965, 49875, 51205, 52535, 53865, 55195, 55998, 56737, 57397, 58057]
dynamic_window = [48028, 50011, 51192, 52297, 53670, 54732, 55598, 56794, 57633, 58046]
dynamic_mpc = [47822, 49331, 50720, 51834, 52557, 53365, 53940, 54739, 55407, 55647]
reinforcement_learning = [47494.04055, 49158.03209, 50508.03209, 51829.50604, 53099.50604,
                          54369.50604, 55605.42788, 56835.42788, 58065.42788, 59295.42788]

# Number of checkpoints data
static_window_checkpoints = [199, 133, 133, 133, 133, 133, 79, 66, 66, 66]
dynamic_window_checkpoints = [344, 202, 135, 133, 112, 101, 90, 94, 93, 84]
dynamic_mpc_checkpoints = [335, 180, 141, 123, 94, 84, 79, 68, 64, 57]
reinforcement_learning_checkpoints = [186, 135, 135, 127, 127, 127, 123, 123, 123, 123]

# Create a figure and a set of subplots
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot total duration on the first y-axis
ax1.plot(checkpoint_penalty, static_window, label="Static Window - Duration", marker='o', color='b')
ax1.plot(checkpoint_penalty, dynamic_window, label="Dynamic Window - Duration", marker='o', color='g')
ax1.plot(checkpoint_penalty, dynamic_mpc, label="Dynamic MPC - Duration", marker='o', color='r')
ax1.plot(checkpoint_penalty, reinforcement_learning, label="Reinforcement Learning - Duration", marker='o', color='c')

# Set labels for the first y-axis
ax1.set_xlabel("Checkpoint Penalty (s)")
ax1.set_ylabel("Total Duration (s)", color='black')
ax1.tick_params(axis='y', labelcolor='black')
ax1.set_ylim(40000, 65000)  # Set the limit for the left y-axis

# Create a second y-axis sharing the same x-axis
ax2 = ax1.twinx()

# Plot number of checkpoints on the second y-axis
ax2.plot(checkpoint_penalty, static_window_checkpoints, label="Static Window - Checkpoints", marker='x', linestyle='--', color='b')
ax2.plot(checkpoint_penalty, dynamic_window_checkpoints, label="Dynamic Window - Checkpoints", marker='x', linestyle='--', color='g')
ax2.plot(checkpoint_penalty, dynamic_mpc_checkpoints, label="Dynamic MPC - Checkpoints", marker='x', linestyle='--', color='r')
ax2.plot(checkpoint_penalty, reinforcement_learning_checkpoints, label="Reinforcement Learning - Checkpoints", marker='x', linestyle='--', color='c')

# Set labels for the second y-axis
ax2.set_ylabel("Number of Checkpoints", color='black')
ax2.tick_params(axis='y', labelcolor='black')
ax2.set_ylim(0, 500)  # Set the limit for the right y-axis

# Adding title and legends
fig.suptitle("Checkpoint Penalty vs Total Duration and Number of Checkpoints")
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')

# Show all checkpoint penalties on the x-axis
plt.xticks(checkpoint_penalty)

# Add grid for clarity
ax1.grid(visible=True, linestyle='--', alpha=0.5)

# Display the plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data from the user
tasks = [3, 4, 5, 6, 7, 8]
static_window = [20413, 23039, 27745, 33898, 40184, 49875]
dynamic_mpc = [17739, 20344, 26667, 30632, 40539, 49331]
dynamic_window = [17751, 21680, 26799, 32103, 40790, 50011]
rl = [20528, 23495, 28642, 32238, 40642, 49158]

# Plotting the data
plt.figure(figsize=(10, 6))

plt.plot(tasks, static_window, marker='o', color='red', label='Static Window')
plt.plot(tasks, dynamic_mpc, marker='o', color='blue', label='Dynamic MPC')
plt.plot(tasks, dynamic_window, marker='o', color='green', label='Dynamic Window')
plt.plot(tasks, rl, marker='o', color='black', label='RL')

plt.title("Best Results at Each Task and Strategy Level", fontsize=14)
plt.xlabel("Number of Tasks", fontsize=12)
plt.ylabel("Best Result", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=10)
plt.tight_layout()

# Show plot
plt.show()

import matplotlib.pyplot as plt

# Data for the left-side plot
tasks = [3, 4, 5, 6, 7, 8]
static_window = [20413, 23039, 27745, 33898, 40184, 49875]
dynamic_mpc = [17739, 20344, 26667, 30632, 40539, 49331]
dynamic_window = [17751, 21680, 26799, 32103, 40790, 50011]
rl = [20528, 23495, 28642, 32238, 40642, 49158]

# Data for the right-side plot
static_window_right = [39, 39, 39, 39, 39, 39]
dynamic_mpc_right = [1, 25, 66, 124, 132, 180]
dynamic_window_right = [94, 99, 109, 141, 140, 172]
rl_right = [0, 3, 17, 26, 71, 123]

# Create the figure and the left y-axis
fig, ax1 = plt.subplots(figsize=(12, 6))

# Plot data on the left y-axis
ax1.plot(tasks, static_window, marker='o', color='red', label='Static Window - Duration')
ax1.plot(tasks, dynamic_mpc, marker='o', color='blue', label='Dynamic MPC - Duration ')
ax1.plot(tasks, dynamic_window, marker='o', color='green', label='Dynamic Window - Duration ')
ax1.plot(tasks, rl, marker='o', color='black', label='RL - Duration ')
ax1.set_xlabel("Number of Tasks", fontsize=12)
ax1.set_ylabel("Total Duration (s)", fontsize=12, color='black')
ax1.tick_params(axis='y', labelcolor='black')
ax1.set_ylim(0, 65000)  # Set the y-axis range for the left axis
ax1.grid(True, linestyle='--', alpha=0.6)

# Create the right y-axis
ax2 = ax1.twinx()
ax2.plot(tasks, static_window_right, marker='x', color='red', linestyle='--', label='Static Window - Checkpoints ')
ax2.plot(tasks, dynamic_mpc_right, marker='x', color='blue', linestyle='--', label='Dynamic MPC - Checkpoints ')
ax2.plot(tasks, dynamic_window_right, marker='x', color='green', linestyle='--', label='Dynamic Window - Checkpoints ')
ax2.plot(tasks, rl_right, marker='x', color='black', linestyle='--', label='RL - Checkpoints ')
ax2.set_ylabel("Number of Checkpoints", fontsize=12, color='black')
ax2.tick_params(axis='y', labelcolor='black')
ax2.set_ylim(0, 400)  # Set the y-axis range for the right axis

# Adjust legend positions
left_legend = ax1.legend(loc='upper left', bbox_to_anchor=(0, 1), fontsize=10)
right_legend = ax2.legend(loc='upper right', bbox_to_anchor=(1, 1), fontsize=10)

# Title and layout
plt.title("Best Results at Each Task and Strategy Level", fontsize=14)
plt.tight_layout()

# Show plot
plt.show()

import matplotlib.pyplot as plt

# Data for the left-side plot
tasks = [3, 4, 5, 6, 7, 8]
static_window_left = [20413, 23039, 27745, 33898, 40184, 49875]
dynamic_mpc_left = [17739, 20344, 26667, 30632, 40539, 49331]
dynamic_window_left = [17751, 21680, 26799, 32103, 40790, 50011]
rl_left = [20528, 23495, 28642, 32238, 40642, 49158]

# Data for the right-side plot
static_window_right = [66, 66, 49, 99, 199, 133]
dynamic_mpc_right = [4, 60, 87, 124, 145, 180]
dynamic_window_right = [101, 133, 135, 152, 140, 202]
rl_right = [0, 6, 65, 233, 242, 135]

# Create the plot
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot the left y-axis data
ax1.plot(tasks, static_window_left, color='red', marker='o', label='Static Window-Duration')
ax1.plot(tasks, dynamic_mpc_left, color='blue', marker='o', label='Dynamic MPC-Duration')
ax1.plot(tasks, dynamic_window_left, color='green', marker='o', label='Dynamic Window-Duration')
ax1.plot(tasks, rl_left, color='black', marker='o', label='RL-Duration')

ax1.set_xlabel('Tasks')
ax1.set_ylabel('Total Duration(s)', color='black')
ax1.set_ylim(0, 65000)  # Adjust the left y-axis limits
ax1.tick_params(axis='y', labelcolor='black')

# Create a twin y-axis for the right-side data
ax2 = ax1.twinx()
ax2.plot(tasks, static_window_right, color='red', marker='x', linestyle='--', label='Static Window-Checkpoints')
ax2.plot(tasks, dynamic_mpc_right, color='blue', marker='x', linestyle='--', label='Dynamic MPC-Checkpoints')
ax2.plot(tasks, dynamic_window_right, color='green', marker='x', linestyle='--', label='Dynamic Window-Checkpoints')
ax2.plot(tasks, rl_right, color='black', marker='x', linestyle='--', label='RL-Checkpoints')

ax2.set_ylabel('Number of Checkpoints', color='black')
ax2.set_ylim(0, 400)  # Adjust the right y-axis limits
ax2.tick_params(axis='y', labelcolor='black')

# Adjust legend positions
left_legend = ax1.legend(loc='upper left', bbox_to_anchor=(0, 1), fontsize=10)
right_legend = ax2.legend(loc='upper right', bbox_to_anchor=(1, 1), fontsize=10)

# Add grid and title
ax1.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.title('Best Results at Each Task and Strategy Level')

# Show the plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
checkpoint_penalty = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

# Total duration data
static_window = [47965, 49875, 51205, 52535, 53865, 55195, 55998, 56737, 57397, 58057]
dynamic_window = [48028, 50011, 51192, 52297, 53670, 54732, 55598, 56794, 57633, 58046]
dynamic_mpc = [47822, 49331, 50720, 51834, 52557, 53365, 53940, 54739, 55407, 55647]
reinforcement_learning = [47494.04055, 49158.03209, 50508.03209, 51829.50604, 53099.50604,
                          54369.50604, 55605.42788, 56835.42788, 58065.42788, 59295.42788]

# Number of checkpoints data
static_window_checkpoints = [199, 133, 133, 133, 133, 133, 79, 66, 66, 66]
dynamic_window_checkpoints = [344, 202, 135, 133, 112, 101, 90, 94, 93, 84]
dynamic_mpc_checkpoints = [335, 180, 141, 123, 94, 84, 79, 68, 64, 57]
reinforcement_learning_checkpoints = [186, 135, 135, 127, 127, 127, 123, 123, 123, 123]

# Create a figure and a set of subplots
fig, ax1 = plt.subplots(figsize=(12, 6))

# Bar width
bar_width = 2

# Create bar plots for total duration on the first y-axis
x = np.array(checkpoint_penalty)
ax1.bar(x - bar_width*1.5, static_window, width=bar_width, label="Static Window - Duration", color='blue', alpha=0.7)
ax1.bar(x - bar_width/2, dynamic_window, width=bar_width, label="Dynamic Window - Duration", color='green', alpha=0.7)
ax1.bar(x + bar_width/2, dynamic_mpc, width=bar_width, label="Dynamic MPC - Duration", color='red', alpha=0.7)
ax1.bar(x + bar_width*1.5, reinforcement_learning, width=bar_width, label="RL - Duration", color='black', alpha=0.7)

# Set labels for the first y-axis
ax1.set_xlabel("Checkpoint Penalty (s)", fontsize=18)
ax1.set_ylabel("Duration (s)", color='black',fontsize=18)
ax1.tick_params(axis='y', labelcolor='black')
ax1.set_ylim(40000, 65000)  # Set the limit for the left y-axis

# Create a second y-axis sharing the same x-axis
ax2 = ax1.twinx()

# Plot number of checkpoints as line graphs
ax2.plot(checkpoint_penalty, static_window_checkpoints, label="Static Window - Checkpoints", marker='o', linestyle='--', color='blue')
ax2.plot(checkpoint_penalty, dynamic_window_checkpoints, label="Dynamic Window - Checkpoints", marker='^', linestyle='--', color='green')
ax2.plot(checkpoint_penalty, dynamic_mpc_checkpoints, label="Dynamic MPC - Checkpoints", marker='s', linestyle='--', color='red')
ax2.plot(checkpoint_penalty, reinforcement_learning_checkpoints, label="RL - Checkpoints", marker='d', linestyle='--', color='black')

# Set labels for the second y-axis
ax2.set_ylabel("Number of Checkpoints", color='black',fontsize=18)
ax2.tick_params(axis='y', labelcolor='black')
ax2.set_ylim(0, 500)  # Set the limit for the right y-axis
ax2.set_yticks(np.linspace(0, 500, 6))


# Add legends
bars_legend = ax1.legend(loc='upper left', title='Strategy', fontsize=12,  title_fontsize=12)
lines_legend = ax2.legend(loc='upper center', title='Strategy', fontsize=12,  title_fontsize=12)

# Show all checkpoint penalties on the x-axis
plt.xticks(checkpoint_penalty)
ax1.tick_params(axis='x', labelsize=18)
ax1.tick_params(axis='y', labelsize=18)
ax2.tick_params(axis='y', labelsize=18)

# Add grid for clarity
#ax1.grid(visible=True, linestyle='--', alpha=0.5)

# Display the plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Read CSV file
data = pd.read_csv("checkpoint_data.csv")

# Extract columns
checkpoint_penalty = data["CheckpointPenalty"].values

static_window = data["StaticWindowDuration"].values
dynamic_window = data["DynamicWindowDuration"].values
dynamic_mpc = data["DynamicMPCDuration"].values
reinforcement_learning = data["RLDuration"].values

static_window_checkpoints = data["StaticWindowCheckpoints"].values
dynamic_window_checkpoints = data["DynamicWindowCheckpoints"].values
dynamic_mpc_checkpoints = data["DynamicMPCCheckpoints"].values
reinforcement_learning_checkpoints = data["RLCheckpoints"].values


# Create figure
fig, ax1 = plt.subplots(figsize=(12, 6))

bar_width = 2
x = np.array(checkpoint_penalty)

# Bar plots (Duration)
ax1.bar(x - bar_width*1.5, static_window, width=bar_width, label="Static Window - Duration", color='blue', alpha=0.7)
ax1.bar(x - bar_width/2, dynamic_window, width=bar_width, label="Dynamic Window - Duration", color='green', alpha=0.7)
ax1.bar(x + bar_width/2, dynamic_mpc, width=bar_width, label="Dynamic MPC - Duration", color='red', alpha=0.7)
ax1.bar(x + bar_width*1.5, reinforcement_learning, width=bar_width, label="RL - Duration", color='black', alpha=0.7)

ax1.set_xlabel("Checkpoint Penalty (s)", fontsize=18)
ax1.set_ylabel("Duration (s)", fontsize=18)
ax1.set_ylim(40000, 65000)

# Second y-axis
ax2 = ax1.twinx()

# Line plots (Checkpoints)
ax2.plot(checkpoint_penalty, static_window_checkpoints, marker='o', linestyle='--', color='blue', label="Static Window - Checkpoints")
ax2.plot(checkpoint_penalty, dynamic_window_checkpoints, marker='^', linestyle='--', color='green', label="Dynamic Window - Checkpoints")
ax2.plot(checkpoint_penalty, dynamic_mpc_checkpoints, marker='s', linestyle='--', color='red', label="Dynamic MPC - Checkpoints")
ax2.plot(checkpoint_penalty, reinforcement_learning_checkpoints, marker='d', linestyle='--', color='black', label="RL - Checkpoints")

ax2.set_ylabel("Number of Checkpoints", fontsize=18)
ax2.set_ylim(0, 500)
ax2.set_yticks(np.linspace(0, 500, 6))

# Legends
ax1.legend(loc='upper left', fontsize=12)
ax2.legend(loc='upper center', fontsize=12)

plt.xticks(checkpoint_penalty)
ax1.tick_params(axis='both', labelsize=18)
ax2.tick_params(axis='y', labelsize=18)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data for the bar graph (left y-axis)
simulation_lengths = [50, 100, 150, 200, 250, 300, 350, 400]
static = [5736, 12053, 18513, 24635, 31365, 37768, 43692, 49875]
dynamic_mpc = [5688, 11926, 18244, 24301, 30987, 37279, 43147, 50011]
dynamic_window = [5684, 12071, 18483, 24602, 31391, 37768, 43741, 49331]
rl = [5667, 11863, 18166, 24219, 30826, 37180, 43000, 49158]

# Data for the line graph (right y-axis)
line_static = [66, 66, 49, 99, 199, 133, 101, 135]
line_dynamic_mpc = [4, 60, 87, 124, 145, 180, 125, 160]
line_dynamic_window = [101, 133, 135, 152, 140, 202, 178, 155]
line_rl = [0, 6, 65, 233, 242, 135, 156, 110]

# Bar width and positions
bar_width = 0.2
x = np.arange(len(simulation_lengths))

# Create the figure and twin axes
fig, ax1 = plt.subplots(figsize=(12, 6))
ax2 = ax1.twinx()  # Create a secondary y-axis

# Bar graph (left y-axis)
bars1 = ax1.bar(x - bar_width * 1.5, static, bar_width, label='Static Window - Duration', color='blue', alpha=0.7)
bars2 = ax1.bar(x - bar_width * 0.5, dynamic_window, bar_width, label='Dynamic Window - Duration', color='green', alpha=0.7)
bars3 = ax1.bar(x + bar_width * 0.5, dynamic_mpc, bar_width, label='Dynamic MPC - Duration', color='red', alpha=0.7)
bars4 = ax1.bar(x + bar_width * 1.5, rl, bar_width, label='RL - Duration', color='black', alpha=0.7)

# Line graph (right y-axis)
ax2.plot(x, line_static, marker='o', label='Static Window - Checkpoints', color='blue', linestyle='--')
ax2.plot(x, line_dynamic_mpc, marker='s', label='Dynamic MPC - Checkpoints', color='red', linestyle='--')
ax2.plot(x, line_dynamic_window, marker='^', label='Dynamic Window - Checkpoints', color='green', linestyle='--')
ax2.plot(x, line_rl, marker='d', label='RL - Checkpoints', color='black', linestyle='--')

# Customize the left y-axis
ax1.set_xlabel('Superstep', fontsize=18)
ax1.set_ylabel('Duration (s)', fontsize=18)
ax1.set_ylim(0,65000)
ax1.set_xticks(x)
ax1.set_xticklabels(simulation_lengths)
#ax1.grid(axis='y', linestyle='--', alpha=0.7)

# Customize the right y-axis
ax2.set_ylabel('Number of Checkpoints', fontsize=18)
ax2.set_ylim(0, 400)  # Adjust the range for the line graph

# Add legends
bars_legend = ax1.legend(loc='upper left', title='Strategy', fontsize=12, title_fontsize=12)
lines_legend = ax2.legend(loc='upper center', title='Strategy', fontsize=12, title_fontsize=12)
ax2.set_yticks(np.linspace(0, 400, 6))
ax1.set_yticks(np.linspace(0, 65000, 6))

# Set tick font sizes
ax1.tick_params(axis='x', labelsize=18)
ax1.tick_params(axis='y', labelsize=18)
ax2.tick_params(axis='y', labelsize=18)



# Set legends in the same area
#plt.title('Simulation Lenght V/s Total Duration and Number of checkpoints', fontsize=14)
plt.tight_layout()
plt.show()

#Final Code

import matplotlib.pyplot as plt
import numpy as np

# Data for the bar graph (left y-axis)
simulation_lengths = [100, 200, 300, 400, 500, 600, 700, 800]
static = [12053, 24635, 37768, 49875, 62503, 75617, 88740, 101515]
dynamic_window = [12071, 24602, 37768, 50011, 62607, 75777, 89039, 102065]
dynamic_mpc = [11926, 24301, 37279, 49331, 61810, 74829, 87805, 100441]
rl = [11863, 24219, 37180, 49158, 61604, 74447, 87425, 100061]

# Data for the line graph (right y-axis)
line_static = [33, 99, 99, 133, 166, 299, 349, 399]

line_dynamic_mpc = [49, 96, 137, 180, 228, 276, 328, 375]
line_dynamic_window = [45, 88, 151, 202, 253, 304, 355, 406]

line_rl = [34, 76, 105, 135, 181, 246, 288, 328]

# Bar width and positions
bar_width = 0.2
x = np.arange(len(simulation_lengths))

# Create the figure and twin axes
fig, ax1 = plt.subplots(figsize=(12, 6))
ax2 = ax1.twinx()  # Create a secondary y-axis

# Bar graph (left y-axis)
bars1 = ax1.bar(x - bar_width * 1.5, static, bar_width, label='Static Window - Duration', color='blue', alpha=0.7)
bars2 = ax1.bar(x - bar_width * 0.5, dynamic_window, bar_width, label='Dynamic Window - Duration', color='green', alpha=0.7)
bars3 = ax1.bar(x + bar_width * 0.5, dynamic_mpc, bar_width, label='Dynamic MPC - Duration', color='red', alpha=0.7)
bars4 = ax1.bar(x + bar_width * 1.5, rl, bar_width, label='RL - Duration', color='black', alpha=0.7)

# Line graph (right y-axis)
ax2.plot(x, line_static, marker='o', label='Static Window - Checkpoints', color='blue', linestyle='--')
ax2.plot(x, line_dynamic_window, marker='^', label='Dynamic Window - Checkpoints', color='green', linestyle='--')
ax2.plot(x, line_dynamic_mpc, marker='s', label='Dynamic MPC - Checkpoints', color='red', linestyle='--')
ax2.plot(x, line_rl, marker='d', label='RL - Checkpoints', color='black', linestyle='--')

# Customize the left y-axis
ax1.set_xlabel('Number of Superstep(s)', fontsize=18)
ax1.set_ylabel('Duration (s)', fontsize=18)
ax1.set_ylim(0, 120000)
ax1.set_xticks(x)
ax1.set_xticklabels(simulation_lengths)
#ax1.grid(axis='y', linestyle='--', alpha=0.7)

# Customize the right y-axis
ax2.set_ylabel('Number of Checkpoints', fontsize=18)
ax2.set_ylim(0, 800)  # Adjust the range for the line graph
# Set tick font sizes
ax1.tick_params(axis='x', labelsize=18)
ax1.tick_params(axis='y', labelsize=18)
ax2.tick_params(axis='y', labelsize=18)
ax2.set_yticks(np.linspace(0, 800, 6))
ax1.set_yticks(np.linspace(0, 120000, 6))



# Add legends
bars_legend = ax1.legend(loc='upper left', title='Strategy', fontsize=12,  title_fontsize=12)
lines_legend = ax2.legend(loc='upper center', title='Strategy', fontsize=12,  title_fontsize=12)

# Set legends in the same area
#plt.title('Simulation Length vs Total Duration and Number of Checkpoints', fontsize=14)
plt.tight_layout()
plt.show()

#Final Code

import matplotlib.pyplot as plt
import numpy as np

# New data for the bar graph (left y-axis)
Tasks = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
static = [21772, 23094, 30076, 33454, 41009, 49875, 52544, 55252, 58338, 61794, 65630, 69924, 74759, 79573]
dynamic_window = [18365, 23238, 28243, 31764, 41128, 50011, 52840, 55626, 58871, 61750, 66444, 70039, 74499, 80057]
dynamic_mpc = [18824, 22510, 26171, 32262, 39346, 49331, 51950, 54847, 57775, 61151, 65032, 69111, 73679, 79066]
rl = [19295, 24482, 28319, 32187, 39173, 49158, 51802, 54452, 57695, 61052, 64681, 69014, 73701, 78862]

# New data for the line graph (right y-axis)
line_static = [57, 44, 66, 66, 99, 133, 199, 133, 199, 199, 133, 199, 199, 199]
line_dynamic_window = [101, 118, 117, 136, 163, 202, 188, 187, 203, 206, 220, 211, 232, 214]
line_dynamic_mpc = [14, 47, 88, 123, 170, 180, 179, 200, 187, 196, 205, 202, 220, 228]
line_rl = [13, 20, 43, 89, 101, 135, 158, 154, 154, 170, 177, 137, 138, 169]

# Bar width and positions
bar_width = 0.2
x = np.arange(len(Tasks))

# Create the figure and twin axes
fig, ax1 = plt.subplots(figsize=(12, 6))
ax2 = ax1.twinx()  # Create a secondary y-axis

# Bar graph (left y-axis)
bars1 = ax1.bar(x - bar_width * 1.5, static, bar_width, label='Static Window - Duration', color='blue', alpha=0.7)

bars2 = ax1.bar(x - bar_width * 0.5, dynamic_window, bar_width, label='Dynamic Window - Duration', color='green', alpha=0.7)

bars3 = ax1.bar(x + bar_width * 0.5, dynamic_mpc, bar_width, label='Dynamic MPC - Duration', color='red', alpha=0.7)

bars4 = ax1.bar(x + bar_width * 1.5, rl, bar_width, label='RL - Duration', color='black', alpha=0.7)

# Line graph (right y-axis)
ax2.plot(x, line_static, marker='o', label='Static Window - Checkpoints', color='blue', linestyle='--')

ax2.plot(x, line_dynamic_window, marker='^', label='Dynamic Window - Checkpoints', color='green', linestyle='--')

ax2.plot(x, line_dynamic_mpc, marker='s', label='Dynamic MPC - Checkpoints', color='red', linestyle='--')

ax2.plot(x, line_rl, marker='d', label='RL - Checkpoints', color='black', linestyle='--')

# Customize the left y-axis
ax1.set_xlabel('Number of Tasks', fontsize=18)
ax1.set_ylabel('Duration (s)', fontsize=18)
ax1.set_ylim(0, 90000)
ax1.set_xticks(x)
ax1.set_xticklabels(Tasks)
#ax1.grid(axis='y', linestyle='--', alpha=0.7)

# Customize the right y-axis
ax2.set_ylabel('Number of Checkpoints', fontsize=18)
ax2.set_ylim(0, 400)  # Adjust the range for the line graph
ax2.set_yticks(np.linspace(0, 400, 6))

ax1.set_yticks(np.linspace(0, 90000, 6))

# Set tick font sizes
ax1.tick_params(axis='x', labelsize=18)
ax1.tick_params(axis='y', labelsize=18)
ax2.tick_params(axis='y', labelsize=18)



# Add legends
bars_legend = ax1.legend(loc='upper left', title='Strategy', fontsize=12, title_fontsize=12)
lines_legend = ax2.legend(loc='upper center', title='Strategy', fontsize=12,  title_fontsize=12)

# Set legends in the same area
#plt.title('Number of Tasks vs Total Duration and Number of Checkpoints', fontsize=14)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import joblib

# 1. Load your data
# Assuming the dataset is saved as "simulations.csv"
data = pd.read_csv("Simulations.csv")
#print(data)

# 2. Features (X) and Targets (y)
X = data[['Window size', 'No of tasks', 'Simulation length', 'Checkpoint penalty']]
y = data[['Total Duration', 'Number of checkpoints']]


# 3. Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Train the model (MultiOutputRegressor with Random Forest)
model = MultiOutputRegressor(RandomForestRegressor(random_state=42))
model.fit(X_train_scaled, y_train)

# 6. Evaluate the model
y_pred = model.predict(X_test_scaled)
mae_duration = mean_absolute_error(y_test['Total Duration'], y_pred[:, 0])
mae_checkpoints = mean_absolute_error(y_test['Number of checkpoints'], y_pred[:, 1])

print(f"MAE for Total Duration: {mae_duration}")
print(f"MAE for Number of Checkpoints: {mae_checkpoints}")

# 7. Save the model and scaler
joblib.dump(model, "simulation_model.pkl")
joblib.dump(scaler, "scaler.pkl")

# Load the model and scaler
model = joblib.load("simulation_model.pkl")
scaler = joblib.load("scaler.pkl")

# Example input parameters with corrected column names
new_input = pd.DataFrame({
    "Window size": [3],         # Corrected
    "No of tasks": [8],         # Corrected
    "Simulation length": [400],
    "Checkpoint penalty": [15]   # Corrected
})

# Scale the input
new_input_scaled = scaler.transform(new_input)

# Predict total duration and number of checkpoints
predictions = model.predict(new_input_scaled)
total_duration, num_checkpoints = predictions[0]

print(f"Predicted Total Duration: {total_duration}")
print(f"Predicted Number of Checkpoints: {num_checkpoints}")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Load the model and scaler
model = joblib.load("simulation_model.pkl")
scaler = joblib.load("scaler.pkl")

# Load test data (Ensure it has the same preprocessing as training data)
X_test_scaled = scaler.transform(X_test)  # Scale test features
y_test_pred = model.predict(X_test_scaled)  # Get predictions

# Compute error metrics
mae = mean_absolute_error(y_test, y_test_pred)
mse = mean_squared_error(y_test, y_test_pred)
rmse = np.sqrt(mse)  # Root Mean Squared Error
r2 = r2_score(y_test, y_test_pred)  # R-squared score

# Print the results
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

# Load dataset
data = pd.read_csv("/content/Simulations.csv")  # Update with your file path

# Define features and target variables
X = data[['Window size', 'No of tasks', 'Simulation length', 'Checkpoint penalty']]
y = data[['Total Duration', 'Number of checkpoints']]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define models
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha=1.0),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    #"Support Vector Regressor": SVR(kernel='rbf'),
    "XGBoost": XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
}

# Train and evaluate models
results = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    results[name] = {"MAE": mae, "MSE": mse, "RMSE": rmse, "R²": r2}
    print(f"{name} Results:\nMAE: {mae}, MSE: {mse}, RMSE: {rmse}, R²: {r2}\n")

# Save the best performing model
best_model_name = max(results, key=lambda x: results[x]["R²"])
best_model = models[best_model_name]
joblib.dump(best_model, "best_simulation_model.pkl")
joblib.dump(scaler, "best_scaler.pkl")

print(f"Best model: {best_model_name} with R² = {results[best_model_name]['R²']}")

# Load the saved best model and scaler
best_model = joblib.load("best_simulation_model.pkl")
scaler = joblib.load("best_scaler.pkl")

# New data for prediction (e.g., a new simulation setup)
new_data = pd.DataFrame({
    'Window size': [4],
    'No of tasks': [14],
    'Simulation length': [700],
    'Checkpoint penalty': [5]
})

# Scale the new data using the saved scaler
new_data_scaled = scaler.transform(new_data)

# Make predictions using the best model
predictions = best_model.predict(new_data_scaled)

# Output predictions
print("Predictions for Total Duration and Number of checkpoints:", predictions)

import matplotlib.pyplot as plt
import numpy as np

# Data for the bar graph (left y-axis)
Tasks = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
static = [21772, 23094, 30076, 33454, 41009, 49875, 52544, 55252, 58338, 61794, 65630, 69924, 74759, 79573]
dynamic_window = [18365, 23238, 28243, 31764, 41128, 50011, 52840, 55626, 58871, 61750, 66444, 70039, 74499, 80057]
dynamic_mpc = [18824, 22510, 26171, 32262, 39346, 49331, 51950, 54847, 57775, 61151, 65032, 69111, 73679, 79066]
rl = [19295, 24482, 28319, 32187, 39173, 49158, 51802, 54452, 57695, 61052, 64681, 69014, 73701, 78862]

# Data for the line graph (right y-axis)
line_static = [57, 44, 66, 66, 99, 133, 199, 133, 199, 199, 133, 199, 199, 199]
line_dynamic_window = [101, 118, 117, 136, 163, 202, 188, 187, 203, 206, 220, 211, 232, 214]
line_dynamic_mpc = [14, 47, 88, 123, 170, 180, 179, 200, 187, 196, 205, 202, 220, 228]
line_rl = [13, 20, 43, 89, 101, 135, 158, 154, 154, 170, 177, 137, 138, 169]

# Calculate the percentage improvement over static (improvement means lower duration)
dynamic_window_improvement = [(s - d) / s * 100 for d, s in zip(dynamic_window, static)]
dynamic_mpc_improvement = [(s - d) / s * 100 for d, s in zip(dynamic_mpc, static)]
rl_improvement = [(s - d) / s * 100 for d, s in zip(rl, static)]

# Bar width and positions
bar_width = 0.2
x = np.arange(len(Tasks))

# Create the figure and twin axes
fig, ax1 = plt.subplots(figsize=(12, 6))
ax2 = ax1.twinx()  # Create a secondary y-axis

# Bar graph (left y-axis) showing improvement over static
bars1 = ax1.bar(x - bar_width * 1.5, dynamic_window_improvement, bar_width, label='Dynamic Window - Improvement', color='red', alpha=0.7)
bars2 = ax1.bar(x - bar_width * 0.5, dynamic_mpc_improvement, bar_width, label='Dynamic MPC - Improvement', color='green', alpha=0.7)
bars3 = ax1.bar(x + bar_width * 0.5, rl_improvement, bar_width, label='RL - Improvement', color='black', alpha=0.7)

# Line graph (right y-axis)
ax2.plot(x, line_static, marker='o', label='Static Window - Checkpoints', color='blue', linestyle='--')
ax2.plot(x, line_dynamic_mpc, marker='s', label='Dynamic MPC - Checkpoints', color='green', linestyle='--')
ax2.plot(x, line_dynamic_window, marker='^', label='Dynamic Window - Checkpoints', color='red', linestyle='--')
ax2.plot(x, line_rl, marker='d', label='RL - Checkpoints', color='black', linestyle='--')

# Customize the left y-axis
ax1.set_xlabel('Number of Tasks', fontsize=12)
ax1.set_ylabel('Improvement in Duration (%)', fontsize=12)
ax1.set_ylim(-10, 30)  # Show only positive improvements (less duration is better)
ax1.set_xticks(x)
ax1.set_xticklabels(Tasks)
ax1.grid(axis='y', linestyle='--', alpha=0.7)

# Customize the right y-axis
ax2.set_ylabel('Number of Checkpoints', fontsize=12)
ax2.set_ylim(0, 400)  # Adjust the range for the line graph

# Add legends
bars_legend = ax1.legend(loc='upper left', title='Strategy', fontsize=9)
lines_legend = ax2.legend(loc='upper center', title='Strategy', fontsize=9)

# Set legends in the same area
plt.title('Improvement in Duration and Number of Checkpoints', fontsize=14)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the Excel file (assuming it is named 'your_file.xlsx')
data = pd.read_excel('/content/ML static window data.xlsx', sheet_name='Sheet1')

# Extract the Timestep and Task3 columns
timesteps = data['Timestep']
durations = data['Task 3']

# Plotting the data
plt.plot(timesteps, durations)
plt.xlabel('Timestep')
plt.ylabel('Task3 Duration (ms)')
plt.title('Task3 Duration vs. Timestep')
plt.show()

import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

# Load dataset
data = pd.read_csv("/content/DynWinSim.csv")  # Update with your file path

# Define features and target variables
X = data[['Window size', 'No of tasks', 'Simulation lengt', 'Checkpoint penalty']]
y = data[['Total Duration', 'Number of Checkpoints']]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define models
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha=1.0),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    #"Support Vector Regressor": SVR(kernel='rbf'),
    "XGBoost": XGBRegressor(n_estimators=100, learning_rate=0.2, random_state=42)
}

# Train and evaluate models
results = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    results[name] = {"MAE": mae, "MSE": mse, "RMSE": rmse, "R²": r2}
    print(f"{name} Results:\nMAE: {mae}, MSE: {mse}, RMSE: {rmse}, R²: {r2}\n")

# Save the best performing model
best_model_name = max(results, key=lambda x: results[x]["R²"])
best_model = models[best_model_name]
joblib.dump(best_model, "best_simulation_model.pkl")
joblib.dump(scaler, "best_scaler.pkl")

print(f"Best model: {best_model_name} with R² = {results[best_model_name]['R²']}")

# Load the saved best model and scaler
best_model = joblib.load("best_simulation_model.pkl")
scaler = joblib.load("best_scaler.pkl")

# New data for prediction (e.g., a new simulation setup)
new_data = pd.DataFrame({
    'Window size': [4],
    'No of tasks': [14],
    'Simulation lengt': [700],
    'Checkpoint penalty': [45]
})

# Scale the new data using the saved scaler
new_data_scaled = scaler.transform(new_data)

# Make predictions using the best model
predictions = best_model.predict(new_data_scaled)

# Output predictions
print("Predictions for Total Duration and Number of checkpoints:", predictions)